import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { environment } from '../../../environments/environment';
import { Observable } from 'rxjs';
import { CustomHttpResponse } from '../models/httpResponse.model';
import { NafathData } from '../models/user.model';
import { InvestorSignUp } from '../models/investor.model';

const NAFATH_TOKEN: string = "eyJraWQiOiJlbG0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMDA4OTYzMDA5IiwiZmF0aGVyTmFtZSI6Iti52KjYr9in2YTYsdit2YXZhiIsImdlbmRlciI6Ik0iLCJkYXRlT2ZCaXJ0aEciOiIzMC0xMi0xOTc5IiwidHJhbnNJZCI6IjBjYTEwNDY2LTFhMDMtNDRmZC1hZGZiLWI5MjRhYTZmZTRmZiIsImRhdGVPZkJpcnRoSCI6IjEwLTAyLTE0MDAiLCJncmFuZEZhdGhlck5hbWUiOiLYp9it2YXYryIsImlzcyI6Imh0dHBzOlwvXC9uYWZhdGguYXBpLmVsbS5zYSIsIm5hdGlvbmFsaXR5Q29kZSI6MTEzLCJuaW4iOiIxMDA4OTYzMDA5IiwiZW5nbGlzaFRoaXJkTmFtZSI6IkEiLCJpZFZlcnNpb25OdW1iZXIiOjQsImZhbWlseU5hbWUiOiLYudir2YXYp9mGIiwiZXhwIjoxNzI3NTI5ODA0LCJpZElzc3VlUGxhY2UiOiLYo9it2YjYp9mEINin2YTYsdmK2KfYtiAgNCIsImlhdCI6MTcyNzUyOTY1NCwianRpIjoiNDRlZjg2MDEtZDhlNy00YzMwLWE5N2YtZGU1YWYyOTdhMzk5IiwibmF0aW9uYWxBZGRyZXNzIjpbeyJjaXR5IjoiSkVEREFIIiwic2hvcnRBZGRyZXNzIjoiSkVOQTUwMDciLCJhZGRpdGlvbmFsTnVtYmVyIjoiNjY2OSIsInJlZ2lvbk5hbWUiOiJNZWNjYSBBbCBNb2thcmFtYSIsInN0cmVldEwyIjoi2LnYqNiv2KfZhNmF2YTZgyDYqNmGINmH2LTYp9mFIiwiaXNQcmltYXJ5QWRkcmVzcyI6InRydWUiLCJjaXR5SWQiOiIxOCIsInJlZ2lvbk5hbWVMMiI6ItmF2YPYqSDYp9mE2YXZg9ix2YXYqSIsImRpc3RyaWN0TDIiOiLYrdmKINin2YTZhtmH2LbYqSIsInN0cmVldE5hbWUiOiJBYmR1bCBNYWxpayBJYm4gSGlzaGFtIiwicmVnaW9uSWQiOiIyIiwiZGlzdHJpY3QiOiJBbiBOYWhkYWggRGlzdC4iLCJidWlsZGluZ051bWJlciI6IjUwMDciLCJwb3N0Q29kZSI6IjIzNjE1IiwibG9jYXRpb25Db29yZGluYXRlcyI6IjM5LjEzMDM3MjY1IDIxLjYyMTEwNjIzIiwiY2l0eUwyIjoi2KzYr9ipIn0seyJjaXR5IjoiUklZQURIIiwic2hvcnRBZGRyZXNzIjoiUkhUQjgxMzUiLCJhZGRpdGlvbmFsTnVtYmVyIjoiMzEzMCIsInJlZ2lvbk5hbWUiOiJBbCBSaXlhZGgiLCJzdHJlZXRMMiI6Itin2YTYo9it2YXYr9mKIiwiaXNQcmltYXJ5QWRkcmVzcyI6ImZhbHNlIiwiY2l0eUlkIjoiMyIsInJlZ2lvbk5hbWVMMiI6Itin2YTYsdmK2KfYtiIsImRpc3RyaWN0TDIiOiLYrdmKINin2YTYqti52KfZiNmGIiwic3RyZWV0TmFtZSI6IkFsIEFobWFkaSIsInJlZ2lvbklkIjoiMSIsImRpc3RyaWN0IjoiQWwgVGFhd3VuIERpc3QuIiwiYnVpbGRpbmdOdW1iZXIiOiI4MTM1IiwicG9zdENvZGUiOiIxMjQ3OCIsImxvY2F0aW9uQ29vcmRpbmF0ZXMiOiI0Ni42OTc0Mzc1OCAyNC43ODAxNDQ3NiIsImNpdHlMMiI6Itin2YTYsdmK2KfYtiJ9LHsiY2l0eSI6IlJJWUFESCIsInNob3J0QWRkcmVzcyI6IlJIVEE4MDUwIiwiYWRkaXRpb25hbE51bWJlciI6IjMwODIiLCJyZWdpb25OYW1lIjoiQWwgUml5YWRoIiwic3RyZWV0TDIiOiLYp9mE2KPYrdmF2K_ZiiIsImlzUHJpbWFyeUFkZHJlc3MiOiJmYWxzZSIsImNpdHlJZCI6IjMiLCJyZWdpb25OYW1lTDIiOiLYp9mE2LHZitin2LYiLCJkaXN0cmljdEwyIjoi2K3ZiiDYp9mE2KrYudin2YjZhiIsInN0cmVldE5hbWUiOiJBbCBBaG1hZGkiLCJyZWdpb25JZCI6IjEiLCJkaXN0cmljdCI6IkFsIFRhYXd1biBEaXN0LiIsImJ1aWxkaW5nTnVtYmVyIjoiODA1MCIsInBvc3RDb2RlIjoiMTI0NzciLCJsb2NhdGlvbkNvb3JkaW5hdGVzIjoiNDYuNjk3MDYxMjUgMjQuNzc5NDYzMzciLCJjaXR5TDIiOiLYp9mE2LHZitin2LYifV0sImlkRXhwaXJ5RGF0ZUciOiIyOS0wNy0yMDI5IiwiaWRJc3N1ZURhdGUiOiIyMC0wMy0xNDQxIiwiZW5nbGlzaEZpcnN0TmFtZSI6IkhFU0hBTSIsImVuZ2xpc2hMYXN0TmFtZSI6IlVUSE1BTiIsImlkRXhwaXJ5RGF0ZSI6IjE3LTAzLTE0NTEiLCJhdWQiOiJodHRwczpcL1wvc2VydmljZS50YW13ZWVsYWxhd3dhbC5jb21cL2FwaVwvbmFmYXRoLWNhbGxiYWNrIiwiZmlyc3ROYW1lIjoi2YfYtNin2YUiLCJuYmYiOjE3Mjc1Mjk2NTQsIlBlcnNvbklkIjoxMDA4OTYzMDA5LCJuYXRpb25hbGl0eSI6IlNBVSIsIlNlcnZpY2VOYW1lIjoiRGlnaXRhbFNlcnZpY2VFbnJvbGxtZW50V2l0aG91dEJpbyIsImp3a3NfdXJpIjoiaHR0cHM6XC9cL25hZmF0aC5hcGkuZWxtLnNhXC9hcGlcL3YxXC9tZmFcL2p3ayIsImlkSXNzdWVEYXRlRyI6IjE3LTExLTIwMTkiLCJlbmdsaXNoU2Vjb25kTmFtZSI6IkFCRFVMUkFITUFOIiwic3RhdHVzIjoiQ09NUExFVEVEIn0.L4k6HrVrJEMHvFiFCQIWMtgR5eCZUmu4pAgKFM1TzpS69BsX7oUToshvGYVLRofZmPisuItjui93mnZLFXnvCFXWP-YedwnsNalvtjVUjSdwtBSBqYaL9fp154T8MaaD8jr-F0DU1nJhb0SlKZAdw9FfnN5yGfO40LpHbKE6oqjB7nibecCQU5YclEMJHTn-9E7S7EWfWzck8TOdbq_MnGEouRQ5tx_S0zteC1P08AFFfz_4c3MHMGhvz5y2N5sWRY1AHJxUmk9jGj8yFdtUcFRsyHZvUhEWsSM2lhugsQnyawAJsxb82oLYbSdMsmiJLeFIfBZbQSDdu6Pl4PFOiw"

@Injectable({
  providedIn: 'root'
})
export class AuthService {
  private readonly http = inject(HttpClient);



  nafathRequest(nationalId: number) {
    return this.http.get(environment.apiUrl + `/Accounts/NafathRequest?nationalId=${nationalId}`)
  }

  nafathCallback(transId: string): Observable<CustomHttpResponse<NafathData>> {
    return this.http.post<CustomHttpResponse<NafathData>>(environment.apiUrl + `/Accounts/NafathCallback`, { token: NAFATH_TOKEN, transId })
  }

  signupInvestor(investor: InvestorSignUp): Observable<CustomHttpResponse> {
    return this.http.post<CustomHttpResponse>(environment.apiUrl + `/Accounts/SignUpInvestor`, investor)
  }
}
